services:
  app:
    build: .
    restart: on-failure
    container_name: container-order-app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=postgres
      - HOST=0.0.0.0
  postgres:
    image: postgres
    restart: always
    container_name: postgres-order-app
    networks:
      - default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=OrderDb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  db-data:
